### ISSUE TITLE
Mandatory query parameters

### ISSUE THREAD

**Issue by mookkiah** [restsql/restsql#66]
Is there any way we can force the client to provide at least one defined filter (configurable combinations) attribute. We need this when we have a query with joining large data.
For example Assume both Actor and Film has few hundred thousand of rows and user is making GET request on /restsql/res/actor.ext.ActorFilm (even unintentionally). This could affect the performance of the system.
So if we could define few mandatory filter combinations for the resource. And every request should satisfy at least one to get the result.
Example:
• FirstName
• LastName
• rental_date and return_date (when just one parameter is not enough)

Thanks,
Mahendran.

**Comment by restsql** [comment]
It's a good saftey feature enhancement.

I think a simpler approach however would be to cap the max rows for an unbounded query. The limit could be set in the resource metadata and applied if present.

**Comment by mooreds** [comment]
I have done this by proxying my restSQL API through varnish (though apache or a servlet filter would work as well) and then just appending the 'required' parameters before restSQL ever sees the request.

**Comment by mookkiah** [comment]
@restsql 
Limit controls the number of row to be fetched by query. This affects the data quality when parent has 100 children, when we limit to 1, we are getting 1 child from first parent. We need a way to limit get one parent with all its children.

Example
http://localhost:8080/restsql/res/HierManyToMany?_limit=10&_offset=0
returns first actor with 10 movies
http://localhost:8080/restsql/res/HierManyToMany?_limit=20&_offset=0
returns 2 actors, 19 movies (that’s the total movies from actor 1) in first actor and 1 movie in second actor.

**Comment by restsql** [comment]
Yes the limit is applied by the database to the flat query. The framework is demuxing the rows to create the hierarchy. 

Isn't the issue here about safety? You don't want the db/app server/client getting loaded with thousands of records. The limit implemented as is would protect the system. We are only talking about a cap that kicks in if the client doesn't protect against this situation.

If what you really want is an enhancement to the limit feature itself, then let's drive out those requirements.
